eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  zipkin:
    baseUrl: http://192.168.99.100:9411/
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
