server:
  port: 8083
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
spring:
  rabbitmq:
    host: http://192.168.99.100/
    port: 5672
    username: guest
    password: guest
